Rails.application.routes.draw do
  # get 'artists/index'
  # get 'artists/show'
  # get 'artists/update'
  # get 'artists/delete'
  # get 'albums/index'
  # get 'albums/show'
  # get 'albums/update'
  # get 'albums/delete'
  # get 'songs/index'
  # get 'songs/show'
  # get 'songs/update'
  # get 'songs/delete'
  root 'home#index'
end
